apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-backend-access
spec:
  podSelector:
    matchLabels:
      app: telemetry-backend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: telemetry-frontend # Only allow traffic from frontend pods
    ports:
    - protocol: TCP
      port: 8000
